const TOWNS = {
    NONE: "",
    AGGARD: "Aggard",
    AILLE: "Aille",
    ATHENRY: "Athenry",
    ARDRAHAN: "Ardrahan",
    ENNIS: "Ennis",
    BALLINAMANA: "Ballinamana",
    BALLINADEREEN: "Ballinadereen",
    BALLYGARRAUN: "Ballygarraun",
    BALLYMANAGH: "Ballymanagh",
    BELLHARBOUR: "Bellharbour",
    BUNRATTY: "Bunratty",
    BALLYVAUGHAN: "Ballyvaughan",
    BOHEY: "Bohey",
    CLARECASTE: "Clarecaste",
    COROFIN: "Corofin",
    CAHERPEAK: "Caherpeak",
    CLARINBRIDGE: "Clarinbridge",
    CRAUGHWELL: "Craughwell",
    CREGANNA: "Creganna",
    CRUSHEEN: "Crusheen",
    DOORUS: "Doorus",
    GORT: "Gort",
    GALWAY: "Galway",
    KILCOLGAN: "Kilcolgan",
    KILLEENEEN: "Killeeneen",
    KILTIERNAN: "Kiltiernan",
    KINVARA: "Kinvara",
    LABANE: "Labane",
    LISHEENKYLE: "Lisheenkyle",
    LOUGHREA: "Loughrea",
    MAREE: "Maree",
    MONEYMORE: "Moneymore",
    MOYVILLA: "Moyvilla",
    ORANBEG: "Oranbeg",
    ORANMORE: "Oranmore",
    PARKMORE: "Parkmore",
    PETERSWELL: "Peterswell",
    RATHCOSGROVE: "Rathcosgrove",
    RINVILLE: "Rinville",
    ROSSHILL: "Rosshill",
    ROVEAG: "Roveag",
    STRONGFORD: "Strongford",
    THEMILESTONE: "The Milestone",
    TIERNEEVIN: "Tierneevin",
    TULLYLEAGUE: "Tullyleague",
    TUBBER: "Tubber"
}

export default TOWNS;